const GET_ALLBLOGS = "blog:GET_ALLBLOGS"; //BOTH
const ADD_BLOG= "blog:ADD_BLOG";
const UPDATE_BLOG = "blog:UPDATE_BLOG";
const DELETE_BLOG = "blog:DELETE_BLOG";
const GET_BLOG_ID= "blog:GET_BLOG_ID";
const GET_BLOG_TITLECONTENT = "blog:GET_BLOG_TITLECONTENT";//BOTH
const GET_BLOG_TODAY= "blog:GET_BLOG_TODAY";
const GET_BLOG_YESTERDAY= "blog:GET_BLOG_YESTERDAY";

module.exports={GET_ALLBLOGS,ADD_BLOG,UPDATE_BLOG,DELETE_BLOG,GET_BLOG_ID,
    GET_BLOG_TITLECONTENT,GET_BLOG_TODAY,GET_BLOG_YESTERDAY}