// ADMIN CAN DO ALL 
const GET_ALL_USERS = "user:GET_ALL_USERS"; 
const ADD_USER = "user:ADD_USER";
const DELETE_USER = "user:DELETE_USER";
const UPDATE_USER = "user:UPDATE_USER"; //ONLY USER
const GET_USER_ID = "user:GET_USER_ID";
const GET_USER_NAMEEMAIL = "user:GET_USER_NAMEEMAIL";
const GET_USER_AGE = "user:GET_USER_AGE";


module.exports={GET_ALL_USERS,ADD_USER,DELETE_USER,UPDATE_USER,GET_USER_ID,GET_USER_NAMEEMAIL,GET_USER_AGE}
