const { GET_ALLBLOGS, ADD_BLOG, UPDATE_BLOG, DELETE_BLOG, GET_BLOG_ID, GET_BLOG_TITLECONTENT, GET_BLOG_TODAY, GET_BLOG_YESTERDAY } = require('../../modules/blogs/endPoints')
const {DELETE_USER, GET_ALL_USERS, ADD_USER, GET_USER_ID, GET_USER_AGE, GET_USER_NAMEEMAIL}=require('../../modules/users/endPoints')
module.exports=[GET_ALL_USERS,ADD_USER,DELETE_USER,GET_USER_ID,GET_USER_NAMEEMAIL,GET_USER_AGE,
    GET_ALLBLOGS,ADD_BLOG,UPDATE_BLOG,DELETE_BLOG,GET_BLOG_ID,GET_BLOG_TITLECONTENT,GET_BLOG_TODAY,GET_BLOG_YESTERDAY]